In [3]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [17]:
credit_card_data = pd.read_csv('/content/creditcard.csv')

In [18]:
credit_card_data.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [7]:
credit_card_data.sample(10)

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
6354,7575,-0.883409,1.655534,1.760001,1.359433,-0.562446,-0.570271,0.405587,0.063160,0.837249,...,-0.180691,0.031604,-0.002726,0.643282,-0.275629,-0.461535,0.227051,-0.021345,35.00,0.0
264,187,0.066061,0.876263,1.093993,1.556151,-0.072318,-0.671902,0.569707,-0.143791,-0.609469,...,0.159757,0.497797,-0.043266,0.397923,-0.358151,-0.186331,0.135739,0.098840,23.32,0.0
4614,3973,-1.107768,0.012084,2.931366,1.357845,-0.092498,0.629926,-0.486198,-0.232446,2.663993,...,0.052047,1.080164,-0.333097,0.071494,-0.701779,-0.304419,-0.573538,-0.144059,26.04,0.0
6485,7758,-0.995449,1.520976,1.644143,1.187896,-0.286827,-0.939988,0.525993,-0.435961,0.866322,...,-0.252242,-0.201262,0.025990,0.903796,-0.594434,0.199518,-0.630693,-0.315391,3.59,0.0
7518,10278,1.181330,0.355557,0.710944,1.256526,-0.413757,-0.663457,-0.134517,-0.092396,1.179715,...,-0.148889,-0.223526,0.015134,0.435275,0.436711,-0.504420,-0.012341,0.009139,2.50,0.0
7940,10970,1.181636,-0.163202,0.723120,0.157430,-0.679556,-0.331424,-0.544590,-0.017104,1.562543,...,-0.027275,0.074133,-0.083628,0.009423,0.197107,1.033139,-0.100831,-0.004617,39.00,0.0
6831,8643,-0.391768,1.112687,1.331724,-0.078590,0.613770,0.113081,0.547001,0.027506,0.897709,...,-0.402231,-0.796684,-0.085369,-0.839376,-0.167752,0.113317,0.255546,0.103277,4.45,0.0
5565,5693,-0.287352,1.970747,-2.390917,1.690687,0.925917,-1.507827,1.096988,-0.365299,1.721497,...,-0.534951,-0.490058,0.102496,-0.530206,-0.271675,-0.442553,0.147556,-0.298737,76.49,0.0
562,421,-1.397776,0.004573,2.528964,0.648279,-0.196625,0.163190,-0.278296,0.366045,0.435493,...,-0.087222,0.150044,0.322306,0.091753,0.171955,0.509403,0.266858,0.094296,12.41,0.0
5107,4776,-0.513612,1.118848,-0.739261,-0.923878,2.543351,3.167620,-0.036752,1.104157,0.328846,...,-0.094676,-0.290441,-0.115365,0.972621,-0.171731,0.233342,-0.054631,0.071956,2.16,0.0

In [19]:
credit_card_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [20]:
credit_card_data['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

In [21]:
legit = credit_card_data[credit_card_data.Class == 0]
fraud = credit_card_data[credit_card_data.Class == 1]

In [22]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [23]:
credit_card_data.isnull().sum()

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [24]:
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [25]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [27]:
credit_card_data.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [31]:
legit_sample = legit.sample(n=492)

In [32]:
new_database = pd.concat([legit_sample,fraud], axis=0)

In [33]:
new_database.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
93526,64468.0,0.938842,-0.516333,1.211604,1.689370,-0.931187,0.610284,-0.589564,0.150711,1.256151,...,0.096120,0.549074,-0.346107,-0.020473,0.757794,-0.107897,0.078084,0.049743,119.51,0
22472,32263.0,1.194255,-0.129222,-1.202690,0.294000,2.151196,3.619714,-0.391667,0.839878,0.168247,...,-0.161770,-0.499682,-0.158115,1.011711,0.880078,-0.330442,0.018585,0.018682,44.15,0
230670,146433.0,1.315454,-2.217690,-2.413280,-0.789508,-0.359517,-0.283067,0.338709,-0.301100,-0.880818,...,0.583892,0.572983,-0.415566,0.285683,0.086281,-0.092917,-0.148909,0.003043,485.85,0
178518,123663.0,2.137998,-0.001913,-1.478050,0.161747,0.453643,-0.595361,0.229783,-0.325539,0.460066,...,-0.346555,-0.807384,0.200407,-0.976085,-0.125182,0.257109,-0.065327,-0.068468,0.89,0
121417,76183.0,1.131204,-0.056995,-0.357778,0.915695,0.718346,1.161188,0.022524,0.213440,0.105039,...,-0.125596,-0.272613,-0.342457,-1.679991,0.850865,-0.230120,0.024413,-0.000985,66.67,0

In [34]:
new_database.info()

<class 'pandas.core.frame.DataFrame'>
Index: 984 entries, 93526 to 281674
Data columns (total 31 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Time    984 non-null    float64
 1   V1      984 non-null    float64
 2   V2      984 non-null    float64
 3   V3      984 non-null    float64
 4   V4      984 non-null    float64
 5   V5      984 non-null    float64
 6   V6      984 non-null    float64
 7   V7      984 non-null    float64
 8   V8      984 non-null    float64
 9   V9      984 non-null    float64
 10  V10     984 non-null    float64
 11  V11     984 non-null    float64
 12  V12     984 non-null    float64
 13  V13     984 non-null    float64
 14  V14     984 non-null    float64
 15  V15     984 non-null    float64
 16  V16     984 non-null    float64
 17  V17     984 non-null    float64
 18  V18     984 non-null    float64
 19  V19     984 non-null    float64
 20  V20     984 non-null    float64
 21  V21     984 non-null    float64
 22  V22     984 non-null    float64
 23  V23     984 non-null    float64
 24  V24     984 non-null    float64
 25  V25     984 non-null    float64
 26  V26     984 non-null    float64
 27  V27     984 non-null    float64
 28  V28     984 non-null    float64
 29  Amount  984 non-null    float64
 30  Class   984 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 246.0 KB

In [36]:
new_database['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [39]:
x = new_database.drop(columns='Class', axis=1)
y = new_database['Class']

In [40]:
print(x)

            Time        V1        V2        V3        V4        V5        V6  \
93526    64468.0  0.938842 -0.516333  1.211604  1.689370 -0.931187  0.610284
22472    32263.0  1.194255 -0.129222 -1.202690  0.294000  2.151196  3.619714
230670  146433.0  1.315454 -2.217690 -2.413280 -0.789508 -0.359517 -0.283067
178518  123663.0  2.137998 -0.001913 -1.478050  0.161747  0.453643 -0.595361
121417   76183.0  1.131204 -0.056995 -0.357778  0.915695  0.718346  1.161188
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
93526  -0.589564  0.150711  1.256151  ...  0.155581  0.096120  0.549074
22472  -0.391667  0.839878  0.168247  ...  0.034022 -0.161770 -0.499682
230670  0.338709 -0.301100 -0.880818  ...  0.944389  0.583892  0.572983
178518  0.229783 -0.325539  0.460066  ... -0.127908 -0.346555 -0.807384
121417  0.022524  0.213440  0.105039  ...  0.011521 -0.125596 -0.272613
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
93526  -0.346107 -0.020473  0.757794 -0.107897  0.078084  0.049743  119.51
22472  -0.158115  1.011711  0.880078 -0.330442  0.018585  0.018682   44.15
230670 -0.415566  0.285683  0.086281 -0.092917 -0.148909  0.003043  485.85
178518  0.200407 -0.976085 -0.125182  0.257109 -0.065327 -0.068468    0.89
121417 -0.342457 -1.679991  0.850865 -0.230120  0.024413 -0.000985   66.67
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [41]:
print(y)

93526     0
22472     0
230670    0
178518    0
121417    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

In [42]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size= 0.1, stratify=y, random_state=2)

In [43]:
print(x.shape, x_train.shape, x_test.shape)

(984, 30) (885, 30) (99, 30)

In [44]:
model = LogisticRegression()

In [45]:
model.fit(x_train,y_train)

LogisticRegression()

In [46]:
#accuracy on traning data
x_train_prediction = model.predict(x_train)
training_data_accuracy = accuracy_score(x_train_prediction, y_train)

In [48]:
print(training_data_accuracy)

0.9299435028248587

In [52]:
#accuracy on testing data
x_test_prediction = model.predict(x_test)
test_data_accuracy = accuracy_score(x_test_prediction, y_test)

In [53]:
print(test_data_accuracy)

0.898989898989899